[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-utilities"
version = "0.1.6"
description = "Agent Utilities for Pydantic AI Agents"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0.0",
    "pydantic-ai-slim>=0.0.14",
    "PyYAML>=6.0.0",
    "httpx>=0.23.0",
    "fasta2a>=0.1.0",
]

[[project.authors]]
name = "Audel Rouhi"
email = "knucklessg1@gmail.com"

[project.license]
text = "MIT"

[project.optional-dependencies]
mcp = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "fastapi>=0.128.0",
]
agent = [
    "universal-skills>=0.1.0",
    "pydantic-ai-skills>=0.4.0",
    "pydantic-ai-slim[fastmcp,openai,anthropic,groq,mistral,google,huggingface,a2a,ag-ui,web]>=1.60.0",
    "fastapi>=0.128.0",
]
embeddings = [
    "llama-index-core>=0.10.0",
    "llama-index-embeddings-openai>=0.1.0",
    "llama-index-embeddings-huggingface>=0.2.0",
    "llama-index-embeddings-ollama>=0.1.0",
]
all = [
    "agent-utilities[mcp,agent,embeddings]",
    "tree-sitter>=0.23.2",
    "requests>=2.28.1",
    "urllib3>=2.2.2",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
agent_utilities = ["agent/**", "skills/**"]

[tool.setuptools.packages.find]
where = ["."]
